version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/kii_project
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: eva05
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: kii_project
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: eva05
    ports:
      - "5432:5432"
